// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqsGX6s5JtHab9C5o8CDyywHjeNbRSXrM',
    appId: '1:253251048516:web:0faa8758c9cce749e49811',
    messagingSenderId: '253251048516',
    projectId: 'baytech-2750c',
    authDomain: 'baytech-2750c.firebaseapp.com',
    storageBucket: 'baytech-2750c.firebasestorage.app',
    measurementId: 'G-3P1S9P2G9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbl5HV9JmRPV5EQJvGKyyOPAl53tYBv-w',
    appId: '1:253251048516:android:e51531c687d6c250e49811',
    messagingSenderId: '253251048516',
    projectId: 'baytech-2750c',
    storageBucket: 'baytech-2750c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuns0UOEkvsijQt8BrovsOBt5nPTtr1kQ',
    appId: '1:253251048516:ios:12ab7bb8e4df9603e49811',
    messagingSenderId: '253251048516',
    projectId: 'baytech-2750c',
    storageBucket: 'baytech-2750c.firebasestorage.app',
    iosBundleId: 'com.example.baytech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuns0UOEkvsijQt8BrovsOBt5nPTtr1kQ',
    appId: '1:253251048516:ios:12ab7bb8e4df9603e49811',
    messagingSenderId: '253251048516',
    projectId: 'baytech-2750c',
    storageBucket: 'baytech-2750c.firebasestorage.app',
    iosBundleId: 'com.example.baytech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqsGX6s5JtHab9C5o8CDyywHjeNbRSXrM',
    appId: '1:253251048516:web:b3036d6e54c6d012e49811',
    messagingSenderId: '253251048516',
    projectId: 'baytech-2750c',
    authDomain: 'baytech-2750c.firebaseapp.com',
    storageBucket: 'baytech-2750c.firebasestorage.app',
    measurementId: 'G-PX6FGM5WRS',
  );
}
